### ISSUE TITLE
Alternative to Autohotkey for Mac?

### ISSUE THREAD

**Issue by nicolinux** [buildcomics/AHK_keyboard#1]
Thanks for the project. I am trying to replicate the functionality on the Mac and if I understand it correctly, your code should still work since the device acts as a USB keyboard. Do you have an idea/recomendation for a mac tool which can grab the hid events and translate them to keystrokes?

Thanks

**Comment by buildcomics** [comment]
Hello Nico, and I am happy you like the project.
I don't own a Mac, but google gave some suggestions: https://apple.stackexchange.com/questions/153930/autohotkey-equivalent-for-os-x

The other solution would be to code up your own solution. Whatever you do, if you let me know what your working setup is I can put a link to it in the readme for future Mac users!
